# Generated by Django 6.0.7 on 2026-08-03 23:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutParagraph',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('image', models.ImageField(blank=True, upload_to='certs/')),
                ('title', models.CharField(max_length=200)),
                ('issuer', models.CharField(max_length=120)),
                ('date', models.CharField(blank=True, max_length=60)),
                ('verify', models.URLField(blank=True)),
                ('viewable', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('value', models.CharField(max_length=200)),
                ('href', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactIntro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('logo', models.ImageField(blank=True, upload_to='about/')),
                ('school', models.CharField(max_length=200)),
                ('program', models.CharField(blank=True, max_length=200)),
                ('years', models.CharField(blank=True, max_length=60)),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('company', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('date', models.CharField(blank=True, max_length=60)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('summary', models.TextField(blank=True)),
                ('detail', models.TextField(blank=True)),
                ('highlights', models.JSONField(default=list)),
                ('logos', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MarqueeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('identifier', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=60)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('name', models.CharField(max_length=200)),
                ('first_name', models.CharField(max_length=120)),
                ('roles', models.JSONField(default=list)),
                ('tagline', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=60)),
                ('linkedin', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, upload_to='profile/')),
                ('status_pills', models.JSONField(default=list)),
                ('metrics', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('identifier', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=200)),
                ('short_title', models.CharField(blank=True, max_length=200)),
                ('date', models.CharField(blank=True, max_length=60)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('cover', models.ImageField(blank=True, upload_to='projects/')),
                ('tags', models.JSONField(default=list)),
                ('description', models.JSONField(default=list)),
                ('github', models.URLField(blank=True)),
                ('demo', models.URLField(blank=True)),
                ('featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('icon', models.CharField(blank=True, max_length=120)),
                ('name', models.CharField(max_length=120)),
                ('featured', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('title', models.CharField(max_length=120)),
                ('tags', models.JSONField(default=list)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('value', models.IntegerField(default=0)),
                ('suffix', models.CharField(blank=True, max_length=10)),
                ('label', models.CharField(max_length=120)),
                ('icon', models.CharField(blank=True, max_length=60)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatIDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('icon', models.CharField(blank=True, max_length=60)),
                ('title', models.CharField(max_length=120)),
                ('desc', models.TextField()),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('image', models.ImageField(upload_to='projects/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='content.project')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
